name: Keep Streamlit Awake

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  ping-streamlit-app:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit app to keep awake
        run: |
          curl -I https://interactivegames-mmxidmx6kaavpyttsnmkbg.streamlit.app
